version: '3.8'
services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: todolist
      POSTGRES_USER: todolist
      POSTGRES_PASSWORD: todolist
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://todolist:todolist@db:5432/todolist
    depends_on:
      - db
volumes:
  db_data:
